server:
  port: 8081
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

#swagger
springfox:
  documentation:
    swagger:
      v2:
        use-model-v3: false

#database
spring:
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        show_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:mysql://k7b303.p.ssafy.io:3306/nuribom?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: nuribom
      password: 

  # swagger 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

token:
  # 1Day
  expiration_time: 1296000000
  secret: NuriBomSecretCode

api-key:
  weather-rest-api: nuh0BPELXbUkTStC9OTm9Lls5pNt57OSPLalavN784TOwPRzg9BD8YNB8CM1XYqil0HKP2KsJbIP/RmLHgVmTg==
  naver-cloud-sms-access-key: 
  naver-cloud-sms-secret-key: 
  naver-cloud-sms-service-id: 
  naver-cloud-sms-sender-phone: 

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
